[project]
name = "payments"
version = "0.1.0"
description = "Microservicio de pagos para ecommerce"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "django>=5.2.7",
    "djangorestframework>=3.16.1",
    "gunicorn>=23.0.0",
    "psycopg[binary]>=3.2.3",
]
