[project]
name = "catalog"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "django>=5.0",
    "djangorestframework>=3.14",
    "django-filter>=23.0",
    "psycopg2-binary>=2.9",
    "python-dotenv>=1.0"
]
